version: "3.9"
services:
  main:
    image: b3log/siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=${AuthCode}']
    ports:
      - 6806:6806
    volumes:
      - workspace:/siyuan/workspace
    restart: unless-stopped
    env_file: stack-env
volumes:
  workspace:
